application: concord-lunchtime-bball
version: winter-1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /control
  script: bball.app
  login: admin

- url: /_ah/mail/.+ 
  script: bballinmail.py 
  login: admin

- url: /static
  static_dir: static

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  
- url: /admin
  static_files: static/admin.html
  upload: static/admin.html
  
- url: /.*
  script: bball.app

inbound_services:
- mail